export const CREATE = 'CREATE';
export const UPDATE = 'UPDATE';
export const DELETE = 'DELETE';
export const FETCH_ALL= 'FETCH_ALL';

//WE CREATE STRING CONSTANTS BCZ IF THERE IS A TYPO ERROR WE CAN'T CATCH THAT
